#pragma once
#include<coim/IntegralConstant.hpp>
#include<coim/IsArray.hpp>
#include<coim/IsBoundedArray.hpp>
#include<coim/IsConst.hpp>
#include<coim/IsLvalueReference.hpp>
#include<coim/IsPointer.hpp>
#include<coim/IsReference.hpp>
#include<coim/IsRvalueReference.hpp>
#include<coim/IsUnboundedArray.hpp>
#include<coim/IsVolatile.hpp>
#include<coim/RemoveConst.hpp>
#include<coim/RemoveCv.hpp>
#include<coim/RemoveCvref.hpp>
#include<coim/RemoveReference.hpp>
#include<coim/RemoveVolatile.hpp>
#include<coim/bool_constant.hpp>
#include<coim/false_type.hpp>
#include<coim/is_array_v.hpp>
#include<coim/is_bounded_array_v.hpp>
#include<coim/is_const_v.hpp>
#include<coim/is_lvalue_reference_v.hpp>
#include<coim/is_pointer_v.hpp>
#include<coim/is_reference_v.hpp>
#include<coim/is_rvalue_reference_v.hpp>
#include<coim/is_unbounded_array_v.hpp>
#include<coim/is_volatile_v.hpp>
#include<coim/remove_const_t.hpp>
#include<coim/remove_cv_t.hpp>
#include<coim/remove_cvref_t.hpp>
#include<coim/remove_reference_t.hpp>
#include<coim/remove_volatile_t.hpp>
#include<coim/size_t.hpp>
#include<coim/true_type.hpp>
